- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Set hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}

# - name: Remove symlink resolve.conf | Comment this task if you live in outside of Iran :)
#   file:
#     path: "/etc/resolv.conf"
#     state: absent
#   ignore_errors: true
#   when: use_iran == "true"

# - name: Configure resolv.conf | Comment this task if you live in outside of Iran :)
#   template:
#     src: "resolv.conf.j2"
#     dest: "/etc/resolv.conf"
#     mode: "0644"
#   when: use_iran == "true"

- name: Add hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{ inventory_hostname }} localhost"
    owner: root
    group: root
    mode: 0644

- name: Add hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.0.1 {{ inventory_hostname }} localhost"
    owner: root
    group: root
    mode: 0644

- name: Add host entries dynamically
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}.{{ domain }}"
    state: present
  loop: "{{ groups['all'] }}"
  when: hostvars[item].ansible_host is defined

- name: Add additional entries specified in extra_entries
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}.{{ domain }}"
    state: present
  loop: "{{ extra_entries }}"

- name: Install necessary tools
  apt:
    update_cache: true
    name:
      - vim
      - sudo
      - wget
      - curl
      - telnet
      - nload
      - s3cmd
      - cron
      - ipset
      - lvm2
      - python3
      - python3-setuptools
      - python3-pip
      - python3-apt
      - intel-microcode
      - htop
      - tcpdump
      - net-tools
      - screen
      - tmux
      - byobu
      - iftop
      - bmon
      - iperf
      - sysstat
      - ethtool
      - plocate
      - thin-provisioning-tools
      - conntrack
      - stress
      - cpufrequtils
      - rsync
      - xz-utils
      - build-essential
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg-agent
      - iptables-persistent
      - open-iscsi
      - nfs-common
      - tzdata
      - tree
      # - bpytop
    state: latest

- name: Fix broken packages
  apt:
    state: fixed

